### ISSUE TITLE
Deprecated messages only output for one deprecated object per input file

### ISSUE THREAD

**Issue by tophmatthews** [idaholab/moose#6780]
### Description of the enhancement or error report

When multiple deprecated objects are present in an input file, a warning for only one of the objects is printed and the others ignored. This is especially unfortunate if the date of deprecation is past for one of the ignored kernels which usually throws an error
### Rationale for the enhancement or information for reproducing the error

This can be repeated by deprecating the kernels in examples/ex06_transient/src/base/ExampleApp.C by

```
registerDeprecatedObjectName(ExampleConvection, "ExampleConvection", "11/11/2010 00:00");
registerDeprecatedObjectName(ExampleDiffusion, "ExampleDiffusion", "11/11/2010 00:00");
registerDeprecatedObjectName(ExampleTimeDerivative, "ExampleTimeDerivative", "11/11/2016 00:00");
```

and observing that when ex06.i is run, only the warning for ExampleTimeDerivative prints.
### Identified impact

Animals with deprecated objects may see more warnings or errors as this is fixed.

**Comment by permcody** [comment]
I'm sure this is due to the use of `mooseDoOnce()`. It might be a little tricky to fix. Perhaps we should just use `rank == 0` instead.

**Comment by tophmatthews** [comment]
Not a huge deal, but this issue is still valid fyi

**Comment by permcody** [comment]
mooseDoOnce use to work because it declares a new local static variable. However, now that the registration is done in the global registry, it might not be working like it use to. I do consider this a bug and it should be fixed. Thanks for the report.

**Comment by tophmatthews** [comment]
Also needs to be extended to AD objects

**Comment by elementx54** [comment]
> Also needs to be extended to AD objects

Would this also include things like `params.addDeprecatedParam`? Does that work with AD ValidParams?

**Comment by tophmatthews** [comment]
In updating the `master` and `slave` terms, this shows that this is still occurs...

**Comment by GiudGiud** [comment]
@socratesgorilla are you interested in taking that one?
I've hit it recently and it's def a problem.

**Comment by socratesgorilla** [comment]
sure go ahead and assign

**Comment by GiudGiud** [comment]
Great.
I think you ll need to remove a doOnce and clean up the output so that it s not crazy excessive (with the backtraces especially) with multiple deprecated params
